### ISSUE TITLE
国产果冻传媒星空传媒免费观看

### ISSUE THREAD

**Issue by mwude** [mwude/defr#19]
国产果冻传媒星空传媒免费观看

 <a href="http://kgf.3k9m.cc">👉👉👉♥♥点此进入♥备用入口一👈👉👉</a>

国产果冻传媒星空传媒免费观看
闹。”

锦晏：“我没护闹啊，我看闻湛都没怎么吃。”

苏美仙立即看向褚骁。

果然褚骁的脸黑了下来。

女儿从吃饭开始就在关心一个臭小子吃没吃菜，当爹的能高兴才怪。

褚骁：“乖宝，爸爸也没吃饱。”

锦晏立即给褚骁夹了两块肉，“爸爸多吃点，一会让再喝点汤，妈妈炖的蹄花汤可好喝了。”

褚骁心里这才稍稍舒服了一些。

但仅仅是一些。

想到女儿先给闻湛夹了菜，他就很难受。

他难受，就要让别人更难受。

于是之后的时间，就成了他和闻湛两个较量的战场。

晚饭结束的时候，除了闻湛和褚骁，其他人都松了口气。

因为褚骁把闻湛叫去他的书房了。

褚锦晨帮苏美仙洗碗的时候，就有些担心地说：“妈妈，您要不要去书房看看。”

苏美仙：“看什么？”

褚锦晨：“看看闻湛还活着没有。”

苏美仙轻笑，“胡说什么，你爸爸只是在考验他，又不会打他，他现在还没那个资格呢。”

褚锦晨：“……合着您都想这么久远了啊？”

“那不然呢？我有什么办法？”苏美仙说。

语气无奈，俨然已经看透了。

褚锦晨心想也是。

妹妹都不着急，她们就更不急了。

九点半，锦晏都睡了一会了，才听到院里传出了说话的声音。

“闻湛，小心脚下。”

“谢谢苏阿姨，我会注意的。”

闻湛的声音消失在了滴答滴答的雨声中。

锦晏侧起身子听了一会，听见隔壁传来了开灯的声音后才趟回被窝。

没一会儿，墙上又传来了咚咚咚的敲击声。

锦晏仔细辨别了一会，发现闻湛在电码的方式问她睡了没有，脚疼不疼后，就用同样的方式敲了一下墙壁。

这样连续进行了三个来回后，主卧室那边传来了褚骁非常突兀的咳嗽声。

“做贼心虚”的两人同时放下了手

**Comment by wpidv** [comment]
1

**Comment by wpidv** [comment]
111
